import Foundation

enum TokenStepLocalization {
    private(set) static var selectedLanguage: TokenStepLanguage = .system

    static var language: TokenStepLanguage {
        selectedLanguage.resolved
    }

    static var locale: Locale {
        Locale(identifier: language.localeIdentifier)
    }

    static func apply(_ language: TokenStepLanguage) {
        selectedLanguage = language
    }

    static func text(_ key: String) -> String {
        guard language != .zhHans else { return key }
        return translations[language]?[key] ?? key
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        format(key, arguments)
    }

    static func format(_ key: String, _ arguments: [CVarArg]) -> String {
        String(format: text(key), locale: locale, arguments: arguments)
    }

    private static let translations: [TokenStepLanguage: [String: String]] = [
        .en: [
            "自动": "Auto",
            "刘海左侧": "Left of notch",
            "刘海右侧": "Right of notch",
            "菜单栏": "Menu bar",
            "左侧": "Left",
            "右侧": "Right",
            "跟随系统": "Follow System",
            "自动匹配 macOS": "Match macOS",
            "准备更新": "Preparing update",
            "正在下载": "Downloading",
            "正在安装并重启": "Installing and relaunching",
            "更新失败": "Update failed",
            "菜单栏模式": "Menu bar mode",
            "自动：刘海旁": "Auto: beside notch",
            "自动：菜单栏": "Auto: menu bar",
            "鼠标移入后展开浮层": "Hover to expand",
            "鼠标移入后展开 Island": "Hover to expand Island",
            "仅使用右上角菜单栏入口": "Use menu bar only",
            "刷新": "Refresh",
            "打开 TokenStep": "Open TokenStep",
            "设置": "Settings",
            "等待同步": "Waiting to sync",
            "Token 采集超时，请稍后重试": "Token collection timed out. Please try again later.",
            "Token 重新校准未完成，已保留原统计。": "Token recalibration did not complete. The previous totals were preserved.",
            "TokenStep 已按真实增量重新校准历史 Token。数字可能变小，但历史记录没有丢失。": "TokenStep recalibrated historical Token usage using true increments. The number may be lower, but no history was lost.",
            "关闭": "Close",
            "手动": "Manual",
            "%d 分钟": "%d min",
            "1 分钟": "1 min",
            "第 %d 圈": "Lap %d",
            "第 %d 圈 · %@": "Lap %d · %@",
            "已完成 %d 圈": "%d laps completed",
            "已完成 %@": "%@ completed",
            "每圈目标 %@": "%@ per lap",
            "少": "Less",
            "多": "More",
            "活跃": "Active",
            "达标": "Goal",
            "最高": "Best",
            "近 8 个月活动墙": "Last 8 Months",
            "颜色越深，越接近或超过每日目标": "Darker means closer to, or beyond, the daily goal",
            "颜色越深，用量越高；描边是今天": "Darker means more usage; outline marks today",
            "%d 个活跃日": "%d active days",
            "全部明细": "All Details",
            "%d 条记录，向下滚动查看完整历史": "%d records. Scroll down for full history",
            "最近 %d 天，适合保存为截图": "Last %d days, ready for screenshots",
            "日期": "Date",
            "Token 消耗": "Token Usage",
            "消耗金额": "Cost",
            "主力工具": "Main Tool",
            "无": "None",
            "累计 Token 消耗": "Total Token Usage",
            "等待下一次同步": "Waiting for next sync",
            "最近 30 天": "Last 30 Days",
            "颜色越深，圈数越高": "Darker means a higher lap",
            "柱越高，用量越多；颜色代表客户端": "Taller bars mean more usage; colors show clients",
            "柱越高，用量越多": "Taller bars mean more usage",
            "颜色代表客户端": "Colors show clients",
            "今天 %@": "Today %@",
            "/ %@ 每圈": "/ %@ per lap",
            "圈数进度": "Lap Progress",
            "按客户端": "By Client",
            "按模型": "By Model",
            "今日客户端": "Today by Client",
            "今日模型": "Today by Model",
            "今日模型消耗": "Today's Model Usage",
            "按模型查看今日 Token、占比与金额估算": "Today's tokens, share, and estimated cost by model",
            "今日 · %d 个模型": "Today · %d models",
            "占比": "Share",
            "金额估算": "Est. Cost",
            "今日暂无使用记录": "No usage recorded today",
            "已有总量，等待模型明细同步": "Total available; waiting for model details",
            "模型明细同步中": "Syncing model details",
            "未知模型": "Unknown model",
            "其他": "Other",
            "还有 %d 个模型": "%d more models",
            "模型明细合计与今日总量不一致；占比按今日总量计算。": "Model details do not match today's total; shares use today's total.",
            "累计总量分布": "Total distribution",
            "主力模型": "Top Models",
            "本月均值": "Monthly Avg",
            "活跃天数": "Active Days",
            "达标天数": "Goal Days",
            "有 AI 使用的日期": "Days with AI usage",
            "达到每日目标": "Reached daily goal",
            "%d圈完成": "Lap %d done",
            "%@进行中": "%@ in progress",
            "所有本机记录": "All local records",
            "今日": "Today",
            "历史": "History",
            "统计": "Analytics",
            "模型与工具": "Models & Tools",
            "隐私": "Privacy",
            "今日消耗": "Today",
            "历史活动": "History",
            "用量统计": "Analytics",
            "今天的 Token 使用节奏": "Today’s token rhythm",
            "长期节奏和所有历史记录": "Long-term rhythm and all history",
            "按客户端和模型拆开看": "Break down by client and model",
            "只统计数量，不读取内容": "Only counts usage, never reads content",
            "保存当前页 PNG（最近 30 天）": "Save Page PNG (Last 30 Days)",
            "保存当前页 PNG": "Save Page PNG",
            "复制当前页截图": "Copy Page Screenshot",
            "截取当前页": "Capture Page",
            "更新": "Updated",
            "同步中": "Syncing",
            "已同步": "Synced",
            "每天一个亿": "100M a day",
            "本地统计": "Local Only",
            "不上传代码或对话": "No code or chats uploaded",
            "今日 AI 战绩": "Today’s AI Scorecard",
            "昨日 AI 工作成绩单": "Yesterday’s AI Scorecard",
            "今天我和 AI 一起消耗了": "Today I used with AI",
            "昨天我和 AI 一起完成了": "Yesterday I completed with AI",
            "已完成": "Completed",
            "仅供参考": "Reference only",
            "今日来源": "Today Sources",
            "昨日来源": "Yesterday Sources",
            "今日 Token": "Today Token",
            "按 Token 消耗排序": "Sorted by token usage",
            "完成度": "Completion",
            "总完成度": "Total completion",
            "这是一个新的记录日": "This is a new record day",
            "和前一天基本持平": "About the same as the previous day",
            "比前一天多 %@": "%@ more than previous day",
            "比前一天少 %@": "%@ less than previous day",
            "分享今日卡片": "Share Today Card",
            "分享昨日成绩": "Share Yesterday Recap",
            "分享昨日节奏": "Share Yesterday Rhythm",
            "下载今日卡片": "Download Today Card",
            "下载昨日成绩": "Download Yesterday Recap",
            "下载昨日节奏": "Download Yesterday Rhythm",
            "分享战绩卡片": "Share scorecard",
            "截图与分享": "Capture and Share",
            "还没有昨日数据": "No yesterday data yet",
            "昨日节奏还在等待同步": "Yesterday rhythm is waiting for sync",
            "本地 AI 使用节奏": "Local AI usage rhythm",
            "AI Token 使用追踪": "AI Token Usage Tracking",
            "昨日 AI 节奏": "Yesterday AI Rhythm",
            "完整 24h": "Full 24h",
            "24 小时波形": "24-hour waveform",
            "颜色随时段变化，最高柱是峰值": "Color follows time of day; tallest bar is the peak",
            "峰值": "Peak",
            "峰值 %@": "Peak %@",
            "活跃时段": "Active Hours",
            "%d 个时段": "%d hours",
            "昨日 Token": "Yesterday Tokens",
            "夜间占比": "Night Share",
            "最长连续": "Longest Streak",
            "%d 小时": "%d h",
            "全天总量": "Daily total",
            "昨天的完整 AI 协作节拍": "A full-day AI collaboration rhythm",
            "清晨启动型": "Early Starter",
            "上午规划型": "Morning Planner",
            "下午爆发型": "Afternoon Burst",
            "晚间冲刺型": "Evening Sprint",
            "夜间 Agent 型": "Night Agent",
            "双峰推进型": "Double Peak",
            "碎片推进型": "Fragmented Pusher",
            "一波流型": "One-Shot Sprint",
            "稳定巡航型": "Steady Cruiser",
            "低频轻触型": "Light Touch",
            "一早就把 AI 拉进工作台": "Pulled AI into the workspace early",
            "上午定方向，后面稳稳推进": "Set direction in the morning, then kept moving",
            "午后能量拉满，一段时间集中爆发": "Afternoon energy peaked in a focused burst",
            "晚间突然加速，把任务向前顶了一截": "A sudden evening sprint pushed the work forward",
            "夜里交给 Agent，把任务往前推": "Handed work to agents at night",
            "一天两次拉满，节奏很有层次": "Two strong peaks made the day layered",
            "多时段穿插推进，随手就把活干了": "Moved work forward across scattered moments",
            "集中一波解决主要战斗": "Solved the main battle in one concentrated push",
            "稳定巡航，没有明显掉线": "Cruised steadily without dropping off",
            "轻量使用，保留一点 AI 手感": "Light usage, keeping the AI habit warm",
            "投缘搭子：夜间 Agent 型": "Best rhythm mate: Night Agent",
            "投缘搭子：下午爆发型": "Best rhythm mate: Afternoon Burst",
            "投缘搭子：上午规划型": "Best rhythm mate: Morning Planner",
            "投缘搭子：清晨启动型": "Best rhythm mate: Early Starter",
            "投缘搭子：稳定巡航型": "Best rhythm mate: Steady Cruiser",
            "投缘搭子：一波流型": "Best rhythm mate: One-Shot Sprint",
            "投缘搭子：碎片推进型": "Best rhythm mate: Fragmented Pusher",
            "投缘搭子：双峰推进型": "Best rhythm mate: Double Peak",
            "你负责清晨开局，TA 负责夜里收尾。": "You open early; they close at night.",
            "你负责上午定盘，TA 负责下午冲刺。": "You set the plan; they sprint in the afternoon.",
            "你负责午后爆发，TA 负责上午定盘。": "You burst in the afternoon; they set the morning plan.",
            "你负责深夜推进，TA 负责清晨接棒。": "You push at night; they pick it up in the morning.",
            "你负责两次拉满，TA 负责稳定托底。": "You bring two peaks; they keep the baseline steady.",
            "你负责随手推进，TA 负责集中攻坚。": "You move things in pieces; they handle the focused push.",
            "你负责一波攻坚，TA 负责穿插补位。": "You attack in one wave; they fill in the gaps.",
            "你负责稳定巡航，TA 负责制造峰值。": "You cruise steadily; they create the peaks.",
            "你负责保持手感，TA 负责拉开节奏。": "You keep the habit warm; they set the tempo.",
            "让 TokenStep 按你的节奏记录 Token 消耗": "Let TokenStep track token usage at your rhythm",
            "语言": "Language",
            "选择 TokenStep 的显示语言": "Choose how TokenStep speaks to you",
            "当前语言": "Current language",
            "切换后立即生效": "Changes apply immediately",
            "TokenStep · Local usage tracker": "TokenStep · Local usage tracker",
            "每日目标": "Daily Goal",
            "token / 天": "tokens / day",
            "自动刷新": "Auto Refresh",
            "显示入口": "Display Entry",
            "面板可见时按此频率检查；后台会根据供电状态降低频率。": "Visible panels check at this rhythm; background refresh slows down based on power state.",
            "手动更新": "Manual refresh",
            "每 %@": "Every %@",
            "当前节奏": "Current rhythm",
            "显示位置": "Display Position",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "On notch displays, show beside the notch. Otherwise use the menu bar.",
            "主题色": "Theme Color",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "The menu bar, rings, activity wall, and buttons follow the theme.",
            "当前主题": "Current theme",
            "登录后自动启动 TokenStep": "Launch TokenStep at login",
            "请先把 TokenStep 拖到 Applications 后再开启开机启动。": "Move TokenStep to Applications before enabling launch at login.",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "Track quietly like steps, so daily token usage is not missed.",
            "自动更新": "Auto Update",
            "自动检查 TokenStep 新版本": "Check for TokenStep updates automatically",
            "有更新时先提醒你，下载前会确认。": "You will be notified first, and asked before downloading.",
            "检查中": "Checking",
            "检查更新": "Check Updates",
            "正在检查更新": "Checking for updates",
            "已是最新版本": "You're up to date",
            "已是最新版本，点击重新检查": "You're up to date. Click to check again",
            "当前版本 %@，%@ 已检查，点击重新检查": "Version %@ checked at %@. Click to check again",
            "发现新版本 %@，点击查看": "Version %@ is available. Click to view",
            "更新检查失败": "Update check failed",
            "更新检查失败，点击重试": "Update check failed. Click to retry",
            "上次检查 %@": "Last checked %@",
            "查看更新": "View Update",
            "隐私状态": "Privacy Status",
            "本地隐私保护已开启": "Local privacy protection is on",
            "代码与对话不会离开这台 Mac": "Code and chats never leave this Mac",
            "恢复默认": "Reset Defaults",
            "完成": "Done",
            "可更新": "Update available",
            "正在检查": "Checking",
            "尚未检查": "Not checked yet",
            "当前版本 %@": "Current version %@",
            "发现 %@": "Found %@",
            "下载前询问": "Ask before download",
            "仅安装已签名公证版本": "Only install signed and notarized builds",
            "开机启动": "Launch at Login",
            "已开启": "On",
            "已关闭": "Off",
            "下次登录会自动运行": "Runs automatically next login",
            "需要手动启动 App": "Start the app manually",
            "不读取代码与对话": "Does not read code or chats",
            "不默认上传数据": "Does not upload by default",
            "本机": "This Mac",
            "%d 个客户端": "%d clients",
            "截取设置页": "Capture settings",
            "复制设置截图": "Copy settings screenshot",
            "保存设置 PNG": "Save settings PNG",
            "今日 Token 消耗": "Daily Token Usage",
            "每日 Token 消耗追踪": "Daily Token Tracking",
            "Codex 剩余额度": "Codex Quota",
            "Agent 剩余额度": "Agent Quota",
            "Codex 额度显示": "Show Codex Quota",
            "Agent 额度显示": "Show Agent Quota",
            "Agent 消耗榜": "Agent Usage Rank",
            "Agent 消耗榜显示": "Show Agent Usage Rank",
            "显示": "Show",
            "隐藏": "Hide",
            "自动检测": "Auto Detect",
            "已自动显示": "Shown automatically",
            "已显示": "Shown",
            "已手动隐藏": "Hidden manually",
            "未检测到 Token Rank": "Token Rank not detected",
            "不读取身份与榜单": "No identity or rank access",
            "尚未关联": "Not linked",
            "已自动关联": "Automatically linked",
            "安装 Token Rank 后自动识别": "Detected after Token Rank is installed",
            "数据同步": "Data sync",
            "我的消耗": "My Usage",
            "打开榜单": "Open Rank",
            "全部工具": "All tools",
            "打开榜单页": "Open leaderboard",
            "打开个人页": "Open profile",
            "默认关闭": "Off by default",
            "不会请求榜单": "No rank request",
            "榜单地址不可用": "Leaderboard URL unavailable",
            "暂时无法读取榜单": "Leaderboard unavailable",
            "榜单同步失败，显示上次结果": "Sync failed, showing last result",
            "匿名用户": "Anonymous",
            "今日排名": "Today Rank",
            "今日排名 #%d": "Today rank #%d",
            "第 %d / %d · 超过 %d%% 参榜用户": "#%d of %d · Ahead of %d%%",
            "%d 人 · %@": "%d users · %@",
            "今日未上榜": "Not ranked today",
            "榜单暂不可用": "Leaderboard unavailable",
            "点击查看今日榜单": "View today’s leaderboard",
            "点击打开榜单页": "Open leaderboard",
            "今日榜首": "Top today",
            "今日榜单": "Today board",
            "我的今日 Token": "My Today Tokens",
            "全榜今日 Token": "All Today Tokens",
            "主力": "Main",
            "榜单": "Board",
            "上榜：": "Ranked:",
            "实验 Agent 来源": "Experimental Agent Sources",
            "启用 ZCode / Hermes": "Enable ZCode / Hermes",
            "启用 ZCode / Hermes / WorkBuddy": "Enable ZCode / Hermes / WorkBuddy",
            "只读取本地 usage 字段，不读取对话正文。": "Only reads local usage fields, never message content.",
            "已计入实验统计": "Included as experimental",
            "已发现，暂不可统计": "Found, not countable yet",
            "刷新中": "Refreshing",
            "等待刷新": "Waiting for refresh",
            "未发现数据源": "No data source found",
            "暂无可用 usage": "No usable usage yet",
            "结构待适配": "Schema needs support",
            "无法读取": "Unreadable",
            "Agent 工作强度": "Agent Work Intensity",
            "近 7 日均": "7-day avg",
            "打开今日页": "Open Today",
            "Agent Token": "Agent Tokens",
            "5 小时": "5 hours",
            "7 天": "7 days",
            "剩余 %@": "%@ left",
            "重置于 %@": "Resets at %@",
            "等待重置": "Reset pending",
            "即将重置": "Resetting soon",
            "%d 分后重置": "Resets in %d min",
            "约 %d:%02d 后重置": "Resets in about %d:%02d",
            "%d 天后重置": "Resets in %d days",
            "刚刚": "Just now",
            "%d 分钟前": "%d min ago",
            "%d 小时前": "%d hr ago",
            "暂未读取到 Codex 额度": "Codex quota unavailable",
            "暂未读取到 Claude Code 额度": "Claude Code quota unavailable",
            "暂未读取到 Agent 额度": "Agent quota unavailable",
            "打开并登录 Codex 后会自动显示额度。": "Open and sign in to Codex to show quota automatically.",
            "打开并登录 Codex / Claude Code 后会自动显示。": "Open and sign in to Codex / Claude Code to show quota automatically.",
            "复制浮层截图": "Copy popover screenshot",
            "保存浮层 PNG": "Save popover PNG",
            "截取浮层": "Capture popover",
            "细线是每日目标": "Thin line marks the daily goal",
            "手动刷新": "Manual refresh",
            "刷新 %@": "Refresh %@",
            "打开仪表盘": "Open Dashboard",
            "退出": "Quit",
            "青绿": "Green",
            "海蓝": "Ocean",
            "紫藤": "Violet",
            "琥珀": "Amber",
            "石墨": "Graphite",
            "远征": "Voyage",
            "经典": "Classic",
            "奥德赛": "Odyssey",
            "星际": "Interstellar",
            "原版 TokenStep": "Original TokenStep",
            "冷雾 · 骨金 · 火星": "Mist · Bone Gold · Embers",
            "事件视界 · 象牙光": "Event Horizon · Ivory Light",
            "导演剪辑": "Director's Cut",
            "爱琴海冷雾": "Aegean Mist",
            "特洛伊火海": "Trojan Inferno",
            "灰烬神像": "Ash & Marble",
            "按界面自动组合": "Composed for each surface",
            "头盔 · 冷雾 · 深海": "Helmet · Mist · Deep Sea",
            "木马 · 烈火 · 余烬": "Horse · Fire · Embers",
            "神像 · 石纹 · 灰烬": "Relief · Marble · Ash",
            "主题皮肤包": "Theme Skin Pack",
            "经典、奥德赛与引力边界可随时切换": "Switch between Classic, Odyssey, and Event Horizon anytime",
            "奥德赛视觉篇章": "Odyssey Visual Chapter",
            "导演剪辑会为不同界面自动分配冷雾、火海与灰烬。": "Director's Cut assigns mist, fire, and ash to the surfaces where they work best.",
            "引力边界": "Event Horizon",
            "引力边界 · 近距事件视界": "Event Horizon · Close Approach",
            "巨大黑洞、象牙白吸积盘与克制电影色；低亮与减少动态时自动静止。": "A monumental black hole, ivory accretion disk, and restrained cinema color; motion pauses in low-light and Reduce Motion states.",
            "原创动态主题": "Original Motion Theme",
            "经典主题色": "Classic Theme Color",
            "原版 TokenStep 的五种明亮配色": "Five bright palettes from the original TokenStep",
            "默认": "Default",
            "清爽": "Fresh",
            "温暖": "Warm",
            "专注": "Focus",
            "黑盘 · 青铜": "Black dial · Bronze",
            "发现新版本 %@": "New version %@ available",
            "内存占用优化与稳定性改进": "Memory and stability improvements",
            "立即更新": "Update Now",
            "稍后": "Later",
            "TokenStep %@ 可用": "TokenStep %@ Available",
            "安装完成后会自动重启到新版本": "TokenStep will relaunch after installation",
            "更新内容": "What’s New",
            "自动安装到 Applications": "Install to Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "After download, the app in the DMG is verified and replaces the old version",
            "跳过此版本": "Skip Version",
            "安装中": "Installing",
            "安装并重启": "Install & Relaunch",
            "优化 Codex 历史数据读取": "Improved Codex history reading",
            "降低后台刷新 CPU 占用": "Reduced background refresh CPU usage",
            "提升菜单栏同步稳定性": "Improved menu bar sync stability",
            "检查更新失败，请稍后再试。": "Could not check for updates. Please try again later.",
            "新版本没有可下载的 DMG。": "The new version has no downloadable DMG.",
            "下载更新失败，请稍后再试。": "Could not download the update. Please try again later.",
            "新版本未通过签名或公证验证，已停止安装。": "The new version did not pass signing or notarization checks.",
            "自动安装失败，请稍后重试，或手动把 TokenStep 拖到 Applications。": "Automatic install failed. Try again later, or drag TokenStep to Applications manually.",
            "只统计 token 数量": "Only counts token usage",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "Used for daily token usage, trends, and estimated cost.",
            "所有数据文件都保留在这台 Mac 上。": "All data files stay on this Mac.",
            "消耗金额仅供参考": "Cost is only an estimate",
            "按本地价格表粗略估算，不等于真实账单。": "Estimated locally and may not match your real bill.",
            "本地优先": "Local First",
            "本地文件": "Local Files",
            "用量数据": "Usage data",
            "后续如果接入排行榜，会单独做授权和确认，不会默认上传。": "If leaderboard support is added later, it will require separate authorization.",
            "截图": "Screenshot",
            "复制截图": "Copy screenshot",
            "保存 PNG": "Save PNG",
            "TokenStep 更新": "TokenStep Update",
            "未检测到可用屏幕": "No available display detected",
            "当前主屏无刘海，已回到菜单栏": "The main display has no notch, so TokenStep is using the menu bar",
            "截图生成失败，请稍后再试。": "Could not create the screenshot. Please try again later.",
            "PNG 文件生成失败，请稍后再试。": "Could not create the PNG file. Please try again later.",
            "JPG 文件生成失败，请稍后再试。": "Could not create the JPG file. Please try again later.",
            "采集脚本退出码 %d": "Collector exited with code %d",
            "采集脚本退出码 %d：%@": "Collector exited with code %d: %@",
            "切换到%@主题": "Switch to %@ theme",
            "切换到%@主题包": "Switch to the %@ skin pack",
            "切换到%@篇章": "Switch to the %@ chapter",
            "TokenStep 自动更新失败": "TokenStep Auto Update Failed",
            "请手动把 DMG 里的 TokenStep 拖到 Applications。": "Please drag TokenStep from the DMG into Applications manually.",
            "Agent 用量": "Agent usage",
            "%d 个来源": "%d sources",
            "今日还没有 Agent 记录": "No agent activity yet today",
            "来源": "Source",
            "请求": "Reqs",
            "工具": "Tools",
            "缓存": "Cache",
            "订阅额度": "Quotas",
            "暂未读取到额度": "No quota available",
            "全榜今日消耗": "All-rank tokens today",
            "%d 人参榜": "%d ranked",
            "我的今日": "My today",
            "输入": "Input",
            "输出": "Output",
            "今日 Agent 输入": "Today's agent input",
            "今日 Agent 输出": "Today's agent output",
            "命中 %@": "%@ hit",
            "覆盖不完整时不估算": "Hidden when coverage is incomplete",
            "Cursor 代码产出": "Cursor code output",
            "L3 产出信号，不计入圆环": "L3 output signal, not counted in the ring",
            "代码块": "Blocks",
            "模型": "Models",
            "对话": "Chats",
            "文件": "Files",
            "今日暂无": "None today",
            "数据源": "Data sources",
            "L1 · 本地账本": "L1 · Local ledger",
            "L2 · 配额探针": "L2 · Quota probes",
            "L3 · 产出信号": "L3 · Output signals",
            "Cursor 额度": "Cursor quota",
            "已读取": "Ready",
            "额度可用": "Quota ready",
            "缺少数据表": "Missing table",
            "结构无法读取": "Schema unreadable",
            "查询失败": "Query failed",
            "增量缓存异常": "Incremental cache error",
            "未登录": "Signed out",
            "当前 key 非订阅计划": "This key is not a subscription plan",
            "需要 grok login": "Run grok login",
            "暂不可用": "Temporarily unavailable",
            "刚刚成功": "Just now",
            "%d 分钟前成功": "Succeeded %d min ago",
            "%d 小时前成功": "Succeeded %d h ago",
            "历史范围": "History range",
            "%d 天": "%d days",
            "联网项（全部默认关闭）": "Network items (all off by default)",
            "所有新增源默认关闭": "New sources stay off by default",
            "Cursor、GLM、Kimi、Grok 都需要你手动打开。": "Cursor, GLM, Kimi, and Grok must be turned on manually.",
            "其他额度探针": "Other quota probes",
            "GLM / Kimi / Grok 只读取本机登录态，并向对应服务查询剩余额度，失败不影响圆环。": "GLM / Kimi / Grok only read local login state and query remaining quota. Failures never change the ring.",
            "以只读方式读取 state.vscdb 的 accessToken，向 cursor.com 查询额度。Token 不存储、不上传第三方。该接口非官方，可能随时失效。": "Reads the local Cursor access token read-only and queries cursor.com. The token is never stored or uploaded. This unofficial endpoint may break.",
            "只读取 ai_code_hashes 的计数与模型名。不读取代码内容、摘要或任何文件路径。该表每天零点被 Cursor 清空，TokenStep 不做历史留存。": "Reads only counts and model names from ai_code_hashes. No code, summaries, or file paths. Cursor clears this table at midnight; TokenStep does not keep history.",
            "开启 Cursor 额度？": "Enable Cursor quota?",
            "会只读本机 Cursor 登录态，并向 cursor.com 查询额度。Token 不落盘、不上传第三方。该接口非官方，可能随时失效。": "TokenStep will read the local Cursor login state and query cursor.com. The token is never saved or uploaded. This unofficial endpoint may break.",
            "会只读本机 Cursor 登录态，向 cursor.com 查询两档额度和官方用量事件。用量事件会计入圆环。登录态不落盘、不上传第三方。该接口非官方，可能随时失效。": "TokenStep will read the local Cursor login and query cursor.com for two quota pools plus official usage events. Those events join the ring. The login is never saved or uploaded. This unofficial endpoint may break.",
            "开启": "Enable",
            "取消": "Cancel",
            "开启 Cursor 代码产出？": "Enable Cursor code output?",
            "只读取本机 ai_code_hashes 的计数与模型名，不读取代码、摘要或文件路径。该表每天会被 Cursor 清空，TokenStep 不做历史留存。": "Reads only local counts and model names. No code, summaries, or paths. Cursor clears this table daily; TokenStep does not keep history.",
            "未登录 Cursor": "Not signed in to Cursor",
            "未找到 ZAI_API_KEY": "ZAI_API_KEY not found",
            "未配置 GLM API Key": "GLM API key is not set",
            "未登录 Kimi": "Not signed in to Kimi",
            "Kimi 额度暂不可用": "Kimi quota unavailable",
            "Grok 额度暂不可用": "Grok quota unavailable",
            "GLM 额度暂不可用": "GLM quota unavailable",
            "Cursor 额度暂不可用": "Cursor quota unavailable",
            "Cursor 用量暂不可用": "Cursor usage unavailable",
            "Cursor 代码产出暂不可用": "Cursor code output unavailable",
            "读取本机 Codex 登录态": "Uses the local Codex login",
            "读取 Keychain 中的 Claude OAuth": "Reads Claude OAuth from Keychain",
            "只读 state.vscdb 的 accessToken": "Reads accessToken from state.vscdb",
            "两档额度：Cursor 模型 / 其他模型 · 无本地 token": "Two pools: Cursor models / Other models · no local tokens",
            "两档额度 + 官方用量事件计入圆环": "Two quota pools + official usage events in the ring",
            "填写 Coding Plan API Key，只进钥匙串": "Enter a Coding Plan API key. It stays in Keychain.",
            "粘贴 ~/.kimi 的 access_token，不要用开放平台 key": "Paste the ~/.kimi access_token, not a platform key",
            "终端 grok login，或粘贴 session": "Run grok login, or paste a session",
            "浏览器里的短码贴回终端，不要贴到这里": "Paste the short code back into Terminal, not here",
            "读取 ~/.grok/auth.json，短码不要贴到 TokenStep": "Reads ~/.grok/auth.json. Do not paste the short code here.",
            "已读取本机 grok login，不需要往这里粘贴任何代码": "Local grok login found. You do not need to paste anything here.",
            "清除密钥只在你往钥匙串里存过内容时才出现。Grok 正常走 ~/.grok/auth.json，一般看不到这个按钮。": "Clear key only appears after something was saved to Keychain. Grok normally uses ~/.grok/auth.json, so this button is usually hidden.",
            "Grok Build 弹出的短码是给终端用的。贴回正在跑 grok login 的窗口，等它显示成功，再点重新检测。": "The short Grok Build code belongs in Terminal. Paste it into the grok login window, wait for success, then tap Recheck.",
            "一般不用填，短码不要贴到这里": "Usually leave empty. Do not paste the short code here.",
            "需要 Coding Plan 的 ZAI_API_KEY": "Needs a Coding Plan ZAI_API_KEY",
            "需要 ~/.kimi 的 OAuth，不要用开放平台 key": "Needs ~/.kimi OAuth, not a Moonshot platform key",
            "需要 grok login 产生的 ~/.grok/auth.json": "Needs ~/.grok/auth.json from grok login",
            "Cursor 模型": "Cursor models",
            "其他模型": "Other models",
            "自有": "Included",
            "圈数进度，颜色不按来源分段": "Lap progress only. Color is not split by source.",
            "Cursor 无本地 token，额度见右栏": "Cursor has no local tokens. See quotas on the right.",
            "Cursor 无本地 token，不在此列": "Cursor has no local tokens, so it is not listed here.",
            "Cursor 官方用量，计入圆环": "Official Cursor usage, counted in the ring",
            "本地账本 + Cursor 官方用量 · 计入圆环": "Local ledger + official Cursor usage · counted in the ring",
            "额度百分比不进圆环。Cursor 开启后，官方 token 事件会计入圆环。": "Quota percents stay out of the ring. After Cursor is on, official token events join it.",
            "官方用量事件计入圆环 · 两档额度另见额度页": "Official usage events join the ring · two quota pools are on the Quotas page",
            "计入圆环": "In the ring",
            "本地无 token 账本 · 官方事件计入圆环": "No local token ledger · official events join the ring",
            "Cursor 额度与官方用量": "Cursor quota and official usage",
            "state.vscdb → cursor.com 事件计入圆环": "state.vscdb → cursor.com events join the ring",
            "额度走网络；官方用量事件计入圆环；代码产出纯本地。": "Quota uses the network; official usage events join the ring; code output stays local.",
            "今日花费含本地估算，以及已开启的 Cursor 官方 charged 金额。额度栏里的美元/百分比不要和圆环花费加在一起。": "Today's spend includes the local estimate plus official Cursor charges when enabled. Do not add quota dollars or percents to ring spend.",
            "本机登录态或手动填写 · 密钥只进钥匙串": "Local login or manual entry · keys stay in Keychain",
            "密钥只保存在钥匙串，不会写入 settings.json": "Keys stay in Keychain, never settings.json",
            "保存并检测": "Save & check",
            "重新检测": "Recheck",
            "清除密钥": "Clear key",
            "已保存在钥匙串，重新输入可覆盖": "Saved in Keychain. Type again to replace.",
            "粘贴 Coding Plan API Key": "Paste Coding Plan API key",
            "粘贴 Kimi access_token": "Paste Kimi access_token",
            "打开 ~/.kimi": "Open ~/.kimi",
            "打开 ~/.grok": "Open ~/.grok",
            "打开终端登录": "Open Terminal login",
            "或粘贴 grok session": "Or paste grok session",
            "Kimi 需要 OAuth，不要用开放平台 key": "Kimi needs OAuth, not a platform key",
            "Grok 需要 grok login，普通 xAI key 无效": "Grok needs grok login. A plain xAI key will not work.",
            "会话": "Session",
            "本周": "This week",
            "本月额度": "Monthly credits",
            "Token 窗": "Token window",
            "花费": "Spend",
            "5小时": "5h",
            "7天": "7d",
            "本月": "Month",
            "网络请求失败": "Network request failed",
            "请求超时": "Request timed out",
            "本版补全：请求数 / 工具调用 / 输出": "Now showing requests, tool calls, and output",
            "模型请求": "Model requests",
            "工具调用": "Tool calls",
            "缓存命中": "Cache hit",
            "缓存读取": "Cache read",
            "今日分时": "Today by hour",
            "来自 hourlyBuckets · 活跃小时由此重算": "From hourlyBuckets · active hours are recalculated here",
            "仅 L1 本地账本 · 计入圆环": "L1 local ledger only · counted in the ring",
            "其他 %d 个来源": "%d other sources",
            "无时间戳 %@ 已单列，不摊进任何小时。": "%@ without timestamps is listed separately and not spread across hours.",
            "L3 · 不计入圆环": "L3 · not in the ring",
            "纯本地 · ai-code-tracking.db": "Local only · ai-code-tracking.db",
            "Cursor 本地没有 token 数，只有产出量。这里回答「AI 帮我写了多少」，不参与 Token 总量。": "Cursor has no local token counts, only output volume. This answers how much AI wrote, and never joins Token totals.",
            "AI 代码块": "AI code blocks",
            "%d 块": "%d blocks",
            "通用": "General",
            "额度": "Quotas",
            "计入圆环与总量": "Counts in the ring",
            "只进额度栏": "Quota column only",
            "独立展示": "Shown separately",
            "去额度页配置": "Configure in Quotas",
            "正常 · %d 请求": "OK · %d requests",
            "已全部去重": "Fully deduped",
            "数据库未找到": "Database not found",
            "读取失败时显示「暂不可用」并保留上次值，绝不显示 0%。": "On failure, show Unavailable and keep the last value. Never show 0%.",
            "预警": "Alerts",
            "额度紧张时的提示强度": "How strongly low quota is flagged",
            "菜单栏预警点": "Menu bar warning dot",
            "任一额度剩余低于阈值时，图标加红点": "Adds a red dot when any remaining quota is below the threshold",
            "阈值": "Threshold",
            "剩余百分比": "Remaining percent",
            "告急卡置顶": "Pin urgent cards",
            "浮窗额度栏把最紧张的排最前": "The popover quota column puts the lowest remaining first",
            "始终启用": "Always on",
            "在 Finder 中显示": "Show in Finder",
            "清除本地数据": "Clear local data",
            "读取": "Reads",
            "不读取": "Does not read",
            "不做": "Does not",
            "日期 · 模型名 · 客户端名 · token 计数": "Dates, model names, client names, token counts",
            "prompt · 代码正文 · 对话内容": "Prompts, source code, conversation text",
            "不开代理 · 不按字数估算 token": "No proxy, and no token estimates from word count",
            "默认不联网、不上传。Token 统计全部来自本机日志。": "No network and no upload by default. Token totals come from local logs.",
            "开启后才会发起请求，逐项独立": "Requests start only after you turn each item on",
            "Codex 额度": "Codex quota",
            "Claude 额度": "Claude quota",
            "本机 codex 登录态": "Local Codex login",
            "钥匙串 OAuth → Anthropic": "Keychain OAuth → Anthropic",
            "state.vscdb token → cursor.com": "state.vscdb token → cursor.com",
            "各自本机凭证": "Each provider's local credentials",
            "仅在开启后上报": "Uploaded only after you opt in",
            "Cursor 明细": "Cursor details",
            "L3 本地": "L3 local",
            "额度走网络，代码产出纯本地，两者独立开关": "Quota uses the network; code output stays local. Separate toggles.",
            "读 accessToken": "Reads accessToken",
            "仅内存 · 不落盘不上传": "Memory only · never saved or uploaded",
            "读代码块计数": "Reads block counts",
            "ai_code_hashes 的 count 与 model": "count and model from ai_code_hashes",
            "明确不读": "Explicitly skipped",
            "tracked_file_content（代码正文）": "tracked_file_content (source code)",
            "conversation_summaries（对话摘要）": "conversation_summaries (chat summaries)",
            "Cursor 的用量接口非官方公开契约，可能随时变更。失效时只影响这一项。": "Cursor's usage API is unofficial and may change. Failure only affects this item.",
            "可直接查看或删除": "You can inspect or delete these files",
            "「花费」是按内置粗略定价的本地估算，用于看趋势，不是账单。Cursor 额度里的美元来自 Cursor 自己的计费口径，两者不要相加。": "Spend next to the ring is a local estimate for trends, not a bill. Cursor quota dollars use Cursor's own billing and must not be added together.",
            "确认清除本地用量数据？": "Clear local usage data?",
            "将删除 usage.json 与本地缓存，设置会保留。下次同步会重新采集。": "This deletes usage.json and local caches. Settings are kept. The next sync will collect again.",
            "清除": "Clear",
            "已清除本地用量数据": "Local usage data cleared",
            "活跃小时": "Active hours",
            "累计": "Lifetime",
            "达标天": "Goal days",
            "今日 %@ · 已达标 %d 圈": "Today %@ · %d laps done",
            "本地日志有可核对的 token 数，才会计入 Token 总量": "Only local logs with verifiable token counts join Token totals",
            "这些工具本地拿不到 token 数，只能读到额度或花费，因此不计入圆环": "These tools have no local token counts, only quota or spend, so they stay out of the ring",
            "不是 token，是「AI 写了多少」。纯本地读取，不计入任何 Token 口径": "Not tokens — how much AI wrote. Local only, never part of Token totals",
            "不读取 tracked_file_content（代码正文）与 conversation_summaries（对话摘要）。": "Does not read tracked_file_content (source) or conversation_summaries.",
            "订阅额度提供商": "Quota providers",
            "全部默认关闭 · 只读本机登录态 · 逐项独立失败": "All off by default · local login only · each can fail alone",
            "实验来源（ZCode / Hermes / WorkBuddy）": "Experimental sources (ZCode / Hermes / WorkBuddy)",
            "实验来源（ZCode / Hermes / DeepSeek Harness / WorkBuddy）": "Experimental sources (ZCode / Hermes / DeepSeek Harness / WorkBuddy)",
            "未启用": "Off",
            "%d 块可读": "%d blocks readable",
            "~/.codex/sessions · JSONL 增量": "~/.codex/sessions · incremental JSONL",
            "~/.claude/projects · 按 message.id 去重": "~/.claude/projects · deduped by message.id",
            "~/.cc-switch/cc-switch.db · 与原生跨源去重": "~/.cc-switch/cc-switch.db · deduped against native logs",
            "~/.zcode/cli/db/db.sqlite · 实验": "~/.zcode/cli/db/db.sqlite · experimental",
            "~/.hermes/state.db · 实验": "~/.hermes/state.db · experimental",
            "~/.workbuddy/projects · 实验": "~/.workbuddy/projects · experimental",
            "DeepSeek Harness 会话压缩档 · 实验": "DeepSeek Harness session archives · experimental",
            "本地无 token 数 · 额度需访问 cursor.com": "No local token counts · quota needs cursor.com",
            "~/.cursor/ai-tracking/ai-code-tracking.db · 只读计数与模型": "~/.cursor/ai-tracking/ai-code-tracking.db · counts and models only",
            "一圈等于多少 Token": "How many tokens make one lap",
            "采集与图表回溯天数（7–365）": "How far collection and charts look back (7–365)",
            "本版新增入口": "New in this version",
            "调大会增加首次采集耗时。": "Larger ranges make the first collection slower.",
            "外观": "Appearance",
            "主题色与语言": "Theme color and language",
            "系统": "System",
            "简体": "Simplified",
            "繁体": "Traditional",
            "菜单栏或灵动岛，二选一": "Menu bar or Dynamic Island, not both",
            "位置": "Placement",
            "后台节奏 · 前台打开时总会即时刷": "Background cadence · opening the app always refreshes now",
            "间隔": "Interval",
            "省电策略": "Power saving",
            "电池或低电量时后台最短 30 分钟": "On battery or Low Power Mode, background refresh is at least 30 minutes",
            "更新与启动": "Updates and startup",
            "发布包": "Release package",
            "GitHub 检查频率暂时受限，请稍后再试。": "GitHub update checks are temporarily rate-limited. Please try again later.",
            "GitHub 检查频率暂时受限，预计 %@ 后恢复。": "GitHub update checks are rate-limited and should recover after %@.",
            "发现新的稳定版本，可直接下载并安装已签名公证的 DMG。": "A new stable release is available. Download and install the signed, notarized DMG.",
            "自动检查更新": "Check for updates automatically",
            "榜": "Rank",
        ],
        .zhHant: [
            "经典": "經典",
            "奥德赛": "奧德賽",
            "星际": "星際",
            "原版 TokenStep": "原版 TokenStep",
            "冷雾 · 骨金 · 火星": "冷霧 · 骨金 · 火星",
            "事件视界 · 象牙光": "事件視界 · 象牙光",
            "导演剪辑": "導演剪輯",
            "爱琴海冷雾": "愛琴海冷霧",
            "特洛伊火海": "特洛伊火海",
            "灰烬神像": "灰燼神像",
            "按界面自动组合": "按介面自動組合",
            "头盔 · 冷雾 · 深海": "頭盔 · 冷霧 · 深海",
            "木马 · 烈火 · 余烬": "木馬 · 烈火 · 餘燼",
            "神像 · 石纹 · 灰烬": "神像 · 石紋 · 灰燼",
            "主题皮肤包": "主題皮膚包",
            "发布包": "發佈包",
            "GitHub 检查频率暂时受限，请稍后再试。": "GitHub 檢查頻率暫時受限，請稍後再試。",
            "GitHub 检查频率暂时受限，预计 %@ 后恢复。": "GitHub 檢查頻率暫時受限，預計 %@ 後恢復。",
            "发现新的稳定版本，可直接下载并安装已签名公证的 DMG。": "發現新的穩定版本，可直接下載並安裝已簽名公證的 DMG。",
            "经典、奥德赛与引力边界可随时切换": "經典、奧德賽與引力邊界可隨時切換",
            "奥德赛视觉篇章": "奧德賽視覺篇章",
            "导演剪辑会为不同界面自动分配冷雾、火海与灰烬。": "導演剪輯會為不同介面自動分配冷霧、火海與灰燼。",
            "引力边界": "引力邊界",
            "引力边界 · 近距事件视界": "引力邊界 · 近距事件視界",
            "巨大黑洞、象牙白吸积盘与克制电影色；低亮与减少动态时自动静止。": "巨大黑洞、象牙白吸積盤與克制電影色；低亮與減少動態時自動靜止。",
            "原创动态主题": "原創動態主題",
            "经典主题色": "經典主題色",
            "原版 TokenStep 的五种明亮配色": "原版 TokenStep 的五種明亮配色",
            "切换到%@主题包": "切換到%@主題包",
            "切换到%@篇章": "切換到%@篇章",
            "简体中文": "簡體中文",
            "自动": "自動",
            "刘海左侧": "瀏海左側",
            "刘海右侧": "瀏海右側",
            "菜单栏": "選單列",
            "左侧": "左側",
            "右侧": "右側",
            "跟随系统": "跟隨系統",
            "自动匹配 macOS": "自動匹配 macOS",
            "准备更新": "準備更新",
            "正在下载": "正在下載",
            "正在安装并重启": "正在安裝並重新啟動",
            "更新失败": "更新失敗",
            "菜单栏模式": "選單列模式",
            "自动：刘海旁": "自動：瀏海旁",
            "自动：菜单栏": "自動：選單列",
            "鼠标移入后展开浮层": "滑鼠移入後展開浮層",
            "仅使用右上角菜单栏入口": "僅使用右上角選單列入口",
            "刷新": "重新整理",
            "打开 TokenStep": "開啟 TokenStep",
            "设置": "設定",
            "等待同步": "等待同步",
            "Token 采集超时，请稍后重试": "Token 採集逾時，請稍後重試",
            "Token 重新校准未完成，已保留原统计。": "Token 重新校準未完成，已保留原統計。",
            "TokenStep 已按真实增量重新校准历史 Token。数字可能变小，但历史记录没有丢失。": "TokenStep 已按真實增量重新校準歷史 Token。數字可能變小，但歷史記錄沒有遺失。",
            "关闭": "關閉",
            "手动": "手動",
            "%d 分钟": "%d 分鐘",
            "1 分钟": "1 分鐘",
            "第 %d 圈": "第 %d 圈",
            "第 %d 圈 · %@": "第 %d 圈 · %@",
            "已完成 %d 圈": "已完成 %d 圈",
            "已完成 %@": "已完成 %@",
            "每圈目标 %@": "每圈目標 %@",
            "少": "少",
            "多": "多",
            "活跃": "活躍",
            "达标": "達標",
            "最高": "最高",
            "近 8 个月活动墙": "近 8 個月活動牆",
            "颜色越深，越接近或超过每日目标": "顏色越深，越接近或超過每日目標",
            "颜色越深，用量越高；描边是今天": "顏色越深，用量越高；描邊是今天",
            "%d 个活跃日": "%d 個活躍日",
            "全部明细": "全部明細",
            "%d 条记录，向下滚动查看完整历史": "%d 條記錄，向下捲動查看完整歷史",
            "最近 %d 天，适合保存为截图": "最近 %d 天，適合儲存為截圖",
            "日期": "日期",
            "Token 消耗": "Token 消耗",
            "消耗金额": "消耗金額",
            "主力工具": "主力工具",
            "无": "無",
            "累计 Token 消耗": "累計 Token 消耗",
            "等待下一次同步": "等待下一次同步",
            "最近 30 天": "最近 30 天",
            "颜色越深，圈数越高": "顏色越深，圈數越高",
            "柱越高，用量越多；颜色代表客户端": "柱越高，用量越多；顏色代表客戶端",
            "柱越高，用量越多": "柱越高，用量越多",
            "颜色代表客户端": "顏色代表客戶端",
            "今天 %@": "今天 %@",
            "/ %@ 每圈": "/ %@ 每圈",
            "圈数进度": "圈數進度",
            "按客户端": "按客戶端",
            "按模型": "按模型",
            "今日客户端": "今日客戶端",
            "今日模型": "今日模型",
            "今日模型消耗": "今日模型消耗",
            "按模型查看今日 Token、占比与金额估算": "按模型查看今日 Token、佔比與金額估算",
            "今日 · %d 个模型": "今日 · %d 個模型",
            "占比": "佔比",
            "金额估算": "金額估算",
            "今日暂无使用记录": "今日暫無使用記錄",
            "已有总量，等待模型明细同步": "已有總量，等待模型明細同步",
            "模型明细同步中": "模型明細同步中",
            "未知模型": "未知模型",
            "其他": "其他",
            "还有 %d 个模型": "還有 %d 個模型",
            "模型明细合计与今日总量不一致；占比按今日总量计算。": "模型明細合計與今日總量不一致；佔比按今日總量計算。",
            "累计总量分布": "累計總量分布",
            "主力模型": "主力模型",
            "本月均值": "本月均值",
            "活跃天数": "活躍天數",
            "达标天数": "達標天數",
            "有 AI 使用的日期": "有 AI 使用的日期",
            "达到每日目标": "達到每日目標",
            "%d圈完成": "%d圈完成",
            "%@进行中": "%@進行中",
            "所有本机记录": "所有本機記錄",
            "今日": "今日",
            "历史": "歷史",
            "统计": "統計",
            "模型与工具": "模型與工具",
            "隐私": "隱私",
            "今日消耗": "今日消耗",
            "历史活动": "歷史活動",
            "用量统计": "用量統計",
            "今天的 Token 使用节奏": "今天的 Token 使用節奏",
            "长期节奏和所有历史记录": "長期節奏和所有歷史記錄",
            "按客户端和模型拆开看": "按客戶端和模型拆開看",
            "只统计数量，不读取内容": "只統計數量，不讀取內容",
            "保存当前页 PNG（最近 30 天）": "儲存目前頁 PNG（最近 30 天）",
            "保存当前页 PNG": "儲存目前頁 PNG",
            "复制当前页截图": "複製目前頁截圖",
            "截取当前页": "擷取目前頁",
            "更新": "更新",
            "同步中": "同步中",
            "已同步": "已同步",
            "每天一个亿": "每天一個億",
            "本地统计": "本地統計",
            "不上传代码或对话": "不上傳程式碼或對話",
            "今日 AI 战绩": "今日 AI 戰績",
            "昨日 AI 工作成绩单": "昨日 AI 工作成績單",
            "今天我和 AI 一起消耗了": "今天我和 AI 一起消耗了",
            "昨天我和 AI 一起完成了": "昨天我和 AI 一起完成了",
            "已完成": "已完成",
            "仅供参考": "僅供參考",
            "今日来源": "今日來源",
            "昨日来源": "昨日來源",
            "今日 Token": "今日 Token",
            "按 Token 消耗排序": "按 Token 消耗排序",
            "完成度": "完成度",
            "总完成度": "總完成度",
            "这是一个新的记录日": "這是一個新的記錄日",
            "和前一天基本持平": "和前一天基本持平",
            "比前一天多 %@": "比前一天多 %@",
            "比前一天少 %@": "比前一天少 %@",
            "分享今日卡片": "分享今日卡片",
            "分享昨日成绩": "分享昨日成績",
            "分享昨日节奏": "分享昨日節奏",
            "下载今日卡片": "下載今日卡片",
            "下载昨日成绩": "下載昨日成績",
            "下载昨日节奏": "下載昨日節奏",
            "分享战绩卡片": "分享戰績卡片",
            "截图与分享": "截圖與分享",
            "还没有昨日数据": "還沒有昨日資料",
            "昨日节奏还在等待同步": "昨日節奏還在等待同步",
            "本地 AI 使用节奏": "本地 AI 使用節奏",
            "AI Token 使用追踪": "AI Token 使用追蹤",
            "昨日 AI 节奏": "昨日 AI 節奏",
            "完整 24h": "完整 24h",
            "24 小时波形": "24 小時波形",
            "颜色随时段变化，最高柱是峰值": "顏色隨時段變化，最高柱是峰值",
            "峰值": "峰值",
            "峰值 %@": "峰值 %@",
            "活跃时段": "活躍時段",
            "%d 个时段": "%d 個時段",
            "昨日 Token": "昨日 Token",
            "夜间占比": "夜間占比",
            "最长连续": "最長連續",
            "%d 小时": "%d 小時",
            "全天总量": "全天總量",
            "昨天的完整 AI 协作节拍": "昨天的完整 AI 協作節拍",
            "清晨启动型": "清晨啟動型",
            "上午规划型": "上午規劃型",
            "下午爆发型": "下午爆發型",
            "晚间冲刺型": "晚間衝刺型",
            "夜间 Agent 型": "夜間 Agent 型",
            "双峰推进型": "雙峰推進型",
            "碎片推进型": "碎片推進型",
            "一波流型": "一波流型",
            "稳定巡航型": "穩定巡航型",
            "低频轻触型": "低頻輕觸型",
            "一早就把 AI 拉进工作台": "一早就把 AI 拉進工作台",
            "上午定方向，后面稳稳推进": "上午定方向，後面穩穩推進",
            "午后能量拉满，一段时间集中爆发": "午後能量拉滿，一段時間集中爆發",
            "晚间突然加速，把任务向前顶了一截": "晚間突然加速，把任務向前頂了一截",
            "夜里交给 Agent，把任务往前推": "夜裡交給 Agent，把任務往前推",
            "一天两次拉满，节奏很有层次": "一天兩次拉滿，節奏很有層次",
            "多时段穿插推进，随手就把活干了": "多時段穿插推進，隨手就把活幹了",
            "集中一波解决主要战斗": "集中一波解決主要戰鬥",
            "稳定巡航，没有明显掉线": "穩定巡航，沒有明顯掉線",
            "轻量使用，保留一点 AI 手感": "輕量使用，保留一點 AI 手感",
            "投缘搭子：夜间 Agent 型": "投緣搭子：夜間 Agent 型",
            "投缘搭子：下午爆发型": "投緣搭子：下午爆發型",
            "投缘搭子：上午规划型": "投緣搭子：上午規劃型",
            "投缘搭子：清晨启动型": "投緣搭子：清晨啟動型",
            "投缘搭子：稳定巡航型": "投緣搭子：穩定巡航型",
            "投缘搭子：一波流型": "投緣搭子：一波流型",
            "投缘搭子：碎片推进型": "投緣搭子：碎片推進型",
            "投缘搭子：双峰推进型": "投緣搭子：雙峰推進型",
            "你负责清晨开局，TA 负责夜里收尾。": "你負責清晨開局，TA 負責夜裡收尾。",
            "你负责上午定盘，TA 负责下午冲刺。": "你負責上午定盤，TA 負責下午衝刺。",
            "你负责午后爆发，TA 负责上午定盘。": "你負責午後爆發，TA 負責上午定盤。",
            "你负责深夜推进，TA 负责清晨接棒。": "你負責深夜推進，TA 負責清晨接棒。",
            "你负责两次拉满，TA 负责稳定托底。": "你負責兩次拉滿，TA 負責穩定托底。",
            "你负责随手推进，TA 负责集中攻坚。": "你負責隨手推進，TA 負責集中攻堅。",
            "你负责一波攻坚，TA 负责穿插补位。": "你負責一波攻堅，TA 負責穿插補位。",
            "你负责稳定巡航，TA 负责制造峰值。": "你負責穩定巡航，TA 負責製造峰值。",
            "你负责保持手感，TA 负责拉开节奏。": "你負責保持手感，TA 負責拉開節奏。",
            "让 TokenStep 按你的节奏记录 Token 消耗": "讓 TokenStep 按你的節奏記錄 Token 消耗",
            "语言": "語言",
            "选择 TokenStep 的显示语言": "選擇 TokenStep 的顯示語言",
            "当前语言": "目前語言",
            "切换后立即生效": "切換後立即生效",
            "TokenStep · Local usage tracker": "TokenStep · 本地用量追蹤器",
            "每日目标": "每日目標",
            "token / 天": "token / 天",
            "自动刷新": "自動重新整理",
            "显示入口": "顯示入口",
            "面板可见时按此频率检查；后台会根据供电状态降低频率。": "面板可見時按此頻率檢查；背景會依供電狀態降低頻率。",
            "手动更新": "手動更新",
            "每 %@": "每 %@",
            "当前节奏": "目前節奏",
            "显示位置": "顯示位置",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "瀏海螢幕顯示在瀏海旁，其他螢幕使用選單列。",
            "主题色": "主題色",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "選單列、圓環、活動牆和按鈕會一起跟隨主題變化。",
            "当前主题": "目前主題",
            "登录后自动启动 TokenStep": "登入後自動啟動 TokenStep",
            "请先把 TokenStep 拖到 Applications 后再开启开机启动。": "請先把 TokenStep 拖到 Applications 後再開啟開機啟動。",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "像步數一樣默默記錄，避免漏掉每天的 Token 消耗。",
            "自动更新": "自動更新",
            "自动检查 TokenStep 新版本": "自動檢查 TokenStep 新版本",
            "有更新时先提醒你，下载前会确认。": "有更新時先提醒你，下載前會確認。",
            "检查中": "檢查中",
            "检查更新": "檢查更新",
            "正在检查更新": "正在檢查更新",
            "已是最新版本": "已是最新版本",
            "已是最新版本，点击重新检查": "已是最新版本，點擊重新檢查",
            "当前版本 %@，%@ 已检查，点击重新检查": "目前版本 %@，%@ 已檢查，點擊重新檢查",
            "发现新版本 %@，点击查看": "發現新版本 %@，點擊查看",
            "更新检查失败": "更新檢查失敗",
            "更新检查失败，点击重试": "更新檢查失敗，點擊重試",
            "上次检查 %@": "上次檢查 %@",
            "查看更新": "查看更新",
            "隐私状态": "隱私狀態",
            "本地隐私保护已开启": "本地隱私保護已開啟",
            "代码与对话不会离开这台 Mac": "程式碼與對話不會離開這台 Mac",
            "恢复默认": "恢復預設",
            "完成": "完成",
            "可更新": "可更新",
            "正在检查": "正在檢查",
            "尚未检查": "尚未檢查",
            "当前版本 %@": "目前版本 %@",
            "发现 %@": "發現 %@",
            "下载前询问": "下載前詢問",
            "仅安装已签名公证版本": "僅安裝已簽名公證版本",
            "开机启动": "開機啟動",
            "已开启": "已開啟",
            "已关闭": "已關閉",
            "下次登录会自动运行": "下次登入會自動執行",
            "需要手动启动 App": "需要手動啟動 App",
            "不读取代码与对话": "不讀取程式碼與對話",
            "不默认上传数据": "不預設上傳資料",
            "本机": "本機",
            "%d 个客户端": "%d 個客戶端",
            "截取设置页": "擷取設定頁",
            "复制设置截图": "複製設定截圖",
            "保存设置 PNG": "儲存設定 PNG",
            "今日 Token 消耗": "今日 Token 消耗",
            "每日 Token 消耗追踪": "每日 Token 消耗追蹤",
            "Codex 剩余额度": "Codex 剩餘額度",
            "Agent 剩余额度": "Agent 剩餘額度",
            "Codex 额度显示": "顯示 Codex 額度",
            "Agent 额度显示": "顯示 Agent 額度",
            "Agent 消耗榜": "Agent 消耗榜",
            "Agent 消耗榜显示": "顯示 Agent 消耗榜",
            "显示": "顯示",
            "隐藏": "隱藏",
            "自动检测": "自動偵測",
            "已自动显示": "已自動顯示",
            "已显示": "已顯示",
            "已手动隐藏": "已手動隱藏",
            "未检测到 Token Rank": "未偵測到 Token Rank",
            "不读取身份与榜单": "不讀取身分與榜單",
            "尚未关联": "尚未關聯",
            "已自动关联": "已自動關聯",
            "安装 Token Rank 后自动识别": "安裝 Token Rank 後自動識別",
            "数据同步": "資料同步",
            "我的消耗": "我的消耗",
            "打开榜单": "開啟榜單",
            "全部工具": "全部工具",
            "打开榜单页": "開啟榜單頁",
            "打开个人页": "開啟個人頁",
            "默认关闭": "預設關閉",
            "不会请求榜单": "不會請求榜單",
            "榜单地址不可用": "榜單地址不可用",
            "暂时无法读取榜单": "暫時無法讀取榜單",
            "榜单同步失败，显示上次结果": "榜單同步失敗，顯示上次結果",
            "匿名用户": "匿名使用者",
            "今日排名": "今日排名",
            "今日排名 #%d": "今日排名 #%d",
            "第 %d / %d · 超过 %d%% 参榜用户": "第 %d / %d · 超過 %d%% 參榜使用者",
            "%d 人 · %@": "%d 人 · %@",
            "今日未上榜": "今日未上榜",
            "榜单暂不可用": "榜單暫不可用",
            "点击查看今日榜单": "點擊查看今日榜單",
            "点击打开榜单页": "點擊開啟榜單頁",
            "今日榜首": "今日榜首",
            "今日榜单": "今日榜單",
            "我的今日 Token": "我的今日 Token",
            "全榜今日 Token": "全榜今日 Token",
            "主力": "主力",
            "榜单": "榜單",
            "上榜：": "上榜：",
            "实验 Agent 来源": "實驗 Agent 來源",
            "启用 ZCode / Hermes": "啟用 ZCode / Hermes",
            "启用 ZCode / Hermes / WorkBuddy": "啟用 ZCode / Hermes / WorkBuddy",
            "只读取本地 usage 字段，不读取对话正文。": "只讀取本地 usage 欄位，不讀取對話正文。",
            "已计入实验统计": "已計入實驗統計",
            "已发现，暂不可统计": "已發現，暫不可統計",
            "刷新中": "刷新中",
            "等待刷新": "等待刷新",
            "未发现数据源": "未發現資料來源",
            "暂无可用 usage": "暫無可用 usage",
            "结构待适配": "結構待適配",
            "无法读取": "無法讀取",
            "Agent 工作强度": "Agent 工作強度",
            "近 7 日均": "近 7 日均",
            "打开今日页": "開啟今日頁",
            "Agent Token": "Agent Token",
            "5 小时": "5 小時",
            "7 天": "7 天",
            "剩余 %@": "剩餘 %@",
            "重置于 %@": "重置於 %@",
            "等待重置": "等待重置",
            "即将重置": "即將重置",
            "%d 分后重置": "%d 分後重置",
            "约 %d:%02d 后重置": "約 %d:%02d 後重置",
            "%d 天后重置": "%d 天後重置",
            "刚刚": "剛剛",
            "%d 分钟前": "%d 分鐘前",
            "%d 小时前": "%d 小時前",
            "暂未读取到 Codex 额度": "暫未讀取到 Codex 額度",
            "暂未读取到 Claude Code 额度": "暫未讀取到 Claude Code 額度",
            "暂未读取到 Agent 额度": "暫未讀取到 Agent 額度",
            "打开并登录 Codex 后会自动显示额度。": "開啟並登入 Codex 後會自動顯示額度。",
            "打开并登录 Codex / Claude Code 后会自动显示。": "開啟並登入 Codex / Claude Code 後會自動顯示。",
            "复制浮层截图": "複製浮層截圖",
            "保存浮层 PNG": "儲存浮層 PNG",
            "截取浮层": "擷取浮層",
            "细线是每日目标": "細線是每日目標",
            "手动刷新": "手動重新整理",
            "刷新 %@": "重新整理 %@",
            "打开仪表盘": "開啟儀表板",
            "退出": "退出",
            "青绿": "青綠",
            "海蓝": "海藍",
            "紫藤": "紫藤",
            "琥珀": "琥珀",
            "石墨": "石墨",
            "远征": "遠征",
            "默认": "預設",
            "清爽": "清爽",
            "温暖": "溫暖",
            "专注": "專注",
            "黑盘 · 青铜": "黑盤 · 青銅",
            "发现新版本 %@": "發現新版本 %@",
            "内存占用优化与稳定性改进": "記憶體佔用最佳化與穩定性改進",
            "立即更新": "立即更新",
            "稍后": "稍後",
            "TokenStep %@ 可用": "TokenStep %@ 可用",
            "安装完成后会自动重启到新版本": "安裝完成後會自動重新啟動到新版本",
            "更新内容": "更新內容",
            "自动安装到 Applications": "自動安裝到 Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "下載後會驗證 DMG 中的 App，並替換舊版本",
            "跳过此版本": "略過此版本",
            "安装中": "安裝中",
            "安装并重启": "安裝並重新啟動",
            "优化 Codex 历史数据读取": "最佳化 Codex 歷史資料讀取",
            "降低后台刷新 CPU 占用": "降低背景重新整理 CPU 佔用",
            "提升菜单栏同步稳定性": "提升選單列同步穩定性",
            "检查更新失败，请稍后再试。": "檢查更新失敗，請稍後再試。",
            "新版本没有可下载的 DMG。": "新版本沒有可下載的 DMG。",
            "下载更新失败，请稍后再试。": "下載更新失敗，請稍後再試。",
            "新版本未通过签名或公证验证，已停止安装。": "新版本未通過簽名或公證驗證，已停止安裝。",
            "自动安装失败，请稍后重试，或手动把 TokenStep 拖到 Applications。": "自動安裝失敗，請稍後重試，或手動把 TokenStep 拖到 Applications。",
            "只统计 token 数量": "只統計 token 數量",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "用於計算今日 Token 消耗、歷史趨勢和消耗金額。",
            "所有数据文件都保留在这台 Mac 上。": "所有資料檔案都保留在這台 Mac 上。",
            "消耗金额仅供参考": "消耗金額僅供參考",
            "按本地价格表粗略估算，不等于真实账单。": "按本地價格表粗略估算，不等於真實帳單。",
            "本地优先": "本地優先",
            "本地文件": "本地檔案",
            "用量数据": "用量資料",
            "后续如果接入排行榜，会单独做授权和确认，不会默认上传。": "後續如果接入排行榜，會單獨做授權和確認，不會預設上傳。",
            "截图": "截圖",
            "复制截图": "複製截圖",
            "保存 PNG": "儲存 PNG",
            "TokenStep 更新": "TokenStep 更新",
            "未检测到可用屏幕": "未偵測到可用螢幕",
            "当前主屏无刘海，已回到菜单栏": "目前主螢幕無瀏海，已回到選單列",
            "截图生成失败，请稍后再试。": "截圖產生失敗，請稍後再試。",
            "PNG 文件生成失败，请稍后再试。": "PNG 檔案產生失敗，請稍後再試。",
            "JPG 文件生成失败，请稍后再试。": "JPG 檔案產生失敗，請稍後再試。",
            "采集脚本退出码 %d": "採集腳本退出碼 %d",
            "采集脚本退出码 %d：%@": "採集腳本退出碼 %d：%@",
            "切换到%@主题": "切換到%@主題",
            "TokenStep 自动更新失败": "TokenStep 自動更新失敗",
            "请手动把 DMG 里的 TokenStep 拖到 Applications。": "請手動把 DMG 裡的 TokenStep 拖到 Applications。",
            "本版补全：请求数 / 工具调用 / 输出": "本版補全：請求數 / 工具呼叫 / 輸出",
            "模型请求": "模型請求",
            "工具调用": "工具呼叫",
            "缓存命中": "快取命中",
            "缓存读取": "快取讀取",
            "今日分时": "今日分時",
            "来自 hourlyBuckets · 活跃小时由此重算": "來自 hourlyBuckets · 活躍小時由此重算",
            "仅 L1 本地账本 · 计入圆环": "僅 L1 本地帳本 · 計入圓環",
            "本地账本 + Cursor 官方用量 · 计入圆环": "本地帳本 + Cursor 官方用量 · 計入圓環",
            "其他 %d 个来源": "其他 %d 個來源",
            "无时间戳 %@ 已单列，不摊进任何小时。": "無時間戳 %@ 已單列，不攤進任何小時。",
            "L3 · 不计入圆环": "L3 · 不計入圓環",
            "纯本地 · ai-code-tracking.db": "純本地 · ai-code-tracking.db",
            "Cursor 本地没有 token 数，只有产出量。这里回答「AI 帮我写了多少」，不参与 Token 总量。": "Cursor 本地沒有 token 數，只有產出量。這裡回答「AI 幫我寫了多少」，不參與 Token 總量。",
            "AI 代码块": "AI 程式碼塊",
            "%d 块": "%d 塊",
            "通用": "通用",
            "额度": "額度",
            "计入圆环与总量": "計入圓環與總量",
            "只进额度栏": "只進額度欄",
            "独立展示": "獨立展示",
            "去额度页配置": "去額度頁設定",
            "正常 · %d 请求": "正常 · %d 請求",
            "已全部去重": "已全部去重",
            "数据库未找到": "找不到資料庫",
            "读取失败时显示「暂不可用」并保留上次值，绝不显示 0%。": "讀取失敗時顯示「暫不可用」並保留上次值，絕不顯示 0%。",
            "预警": "預警",
            "额度紧张时的提示强度": "額度緊張時的提示強度",
            "菜单栏预警点": "選單列預警點",
            "任一额度剩余低于阈值时，图标加红点": "任一額度剩餘低於閾值時，圖示加紅點",
            "阈值": "閾值",
            "剩余百分比": "剩餘百分比",
            "告急卡置顶": "告急卡置頂",
            "浮窗额度栏把最紧张的排最前": "浮窗額度欄把最緊張的排最前",
            "始终启用": "始終啟用",
            "在 Finder 中显示": "在 Finder 中顯示",
            "清除本地数据": "清除本地資料",
            "读取": "讀取",
            "不读取": "不讀取",
            "不做": "不做",
            "日期 · 模型名 · 客户端名 · token 计数": "日期 · 模型名 · 用戶端名 · token 計數",
            "prompt · 代码正文 · 对话内容": "prompt · 程式碼正文 · 對話內容",
            "不开代理 · 不按字数估算 token": "不開代理 · 不按字數估算 token",
            "默认不联网、不上传。Token 统计全部来自本机日志。": "預設不連網、不上傳。Token 統計全部來自本機日誌。",
            "开启后才会发起请求，逐项独立": "開啟後才會發起請求，逐項獨立",
            "Codex 额度": "Codex 額度",
            "Claude 额度": "Claude 額度",
            "本机 codex 登录态": "本機 codex 登入態",
            "钥匙串 OAuth → Anthropic": "鑰匙圈 OAuth → Anthropic",
            "state.vscdb token → cursor.com": "state.vscdb token → cursor.com",
            "各自本机凭证": "各自本機憑證",
            "仅在开启后上报": "僅在開啟後上報",
            "Cursor 明细": "Cursor 明細",
            "L3 本地": "L3 本地",
            "额度走网络，代码产出纯本地，两者独立开关": "額度走網路，程式產出純本地，兩者獨立開關",
            "额度走网络；官方用量事件计入圆环；代码产出纯本地。": "額度走網路；官方用量事件計入圓環；程式產出純本地。",
            "Cursor 额度与官方用量": "Cursor 額度與官方用量",
            "state.vscdb → cursor.com 事件计入圆环": "state.vscdb → cursor.com 事件計入圓環",
            "今日花费含本地估算，以及已开启的 Cursor 官方 charged 金额。额度栏里的美元/百分比不要和圆环花费加在一起。": "今日花費含本地估算，以及已開啟的 Cursor 官方 charged 金額。額度欄裡的美元/百分比不要和圓環花費加在一起。",
            "读 accessToken": "讀 accessToken",
            "仅内存 · 不落盘不上传": "僅記憶體 · 不落盤不上傳",
            "读代码块计数": "讀程式碼塊計數",
            "ai_code_hashes 的 count 与 model": "ai_code_hashes 的 count 與 model",
            "明确不读": "明確不讀",
            "tracked_file_content（代码正文）": "tracked_file_content（程式碼正文）",
            "conversation_summaries（对话摘要）": "conversation_summaries（對話摘要）",
            "Cursor 的用量接口非官方公开契约，可能随时变更。失效时只影响这一项。": "Cursor 的用量介面非官方公開契約，可能隨時變更。失效時只影響這一項。",
            "可直接查看或删除": "可直接檢視或刪除",
            "「花费」是按内置粗略定价的本地估算，用于看趋势，不是账单。Cursor 额度里的美元来自 Cursor 自己的计费口径，两者不要相加。": "「花費」是按內建粗略定價的本地估算，用於看趨勢，不是帳單。Cursor 額度裡的美元來自 Cursor 自己的計費口徑，兩者不要相加。",
            "确认清除本地用量数据？": "確認清除本地用量資料？",
            "将删除 usage.json 与本地缓存，设置会保留。下次同步会重新采集。": "將刪除 usage.json 與本地快取，設定會保留。下次同步會重新採集。",
            "清除": "清除",
            "已清除本地用量数据": "已清除本地用量資料",
            "活跃小时": "活躍小時",
            "累计": "累計",
            "达标天": "達標天",
            "今日 %@ · 已达标 %d 圈": "今日 %@ · 已達標 %d 圈",
            "本地日志有可核对的 token 数，才会计入 Token 总量": "本地日誌有可核對的 token 數，才會計入 Token 總量",
            "这些工具本地拿不到 token 数，只能读到额度或花费，因此不计入圆环": "這些工具本地拿不到 token 數，只能讀到額度或花費，因此不計入圓環",
            "额度百分比不进圆环。Cursor 开启后，官方 token 事件会计入圆环。": "額度百分比不進圓環。Cursor 開啟後，官方 token 事件會計入圓環。",
            "不是 token，是「AI 写了多少」。纯本地读取，不计入任何 Token 口径": "不是 token，是「AI 寫了多少」。純本地讀取，不計入任何 Token 口徑",
            "不读取 tracked_file_content（代码正文）与 conversation_summaries（对话摘要）。": "不讀取 tracked_file_content（程式碼正文）與 conversation_summaries（對話摘要）。",
            "订阅额度提供商": "訂閱額度提供商",
            "全部默认关闭 · 只读本机登录态 · 逐项独立失败": "全部預設關閉 · 只讀本機登入態 · 逐項獨立失敗",
            "实验来源（ZCode / Hermes / WorkBuddy）": "實驗來源（ZCode / Hermes / WorkBuddy）",
            "实验来源（ZCode / Hermes / DeepSeek Harness / WorkBuddy）": "實驗來源（ZCode / Hermes / DeepSeek Harness / WorkBuddy）",
            "未启用": "未啟用",
            "%d 块可读": "%d 塊可讀",
            "~/.codex/sessions · JSONL 增量": "~/.codex/sessions · JSONL 增量",
            "~/.claude/projects · 按 message.id 去重": "~/.claude/projects · 按 message.id 去重",
            "~/.cc-switch/cc-switch.db · 与原生跨源去重": "~/.cc-switch/cc-switch.db · 與原生跨源去重",
            "~/.zcode/cli/db/db.sqlite · 实验": "~/.zcode/cli/db/db.sqlite · 實驗",
            "~/.hermes/state.db · 实验": "~/.hermes/state.db · 實驗",
            "~/.workbuddy/projects · 实验": "~/.workbuddy/projects · 實驗",
            "DeepSeek Harness 会话压缩档 · 实验": "DeepSeek Harness 會話壓縮檔 · 實驗",
            "本地无 token 数 · 额度需访问 cursor.com": "本地無 token 數 · 額度需訪問 cursor.com",
            "本地无 token 账本 · 官方事件计入圆环": "本地無 token 帳本 · 官方事件計入圓環",
            "两档额度：Cursor 模型 / 其他模型 · 无本地 token": "兩檔額度：Cursor 模型 / 其他模型 · 無本地 token",
            "两档额度 + 官方用量事件计入圆环": "兩檔額度 + 官方用量事件計入圓環",
            "官方用量事件计入圆环 · 两档额度另见额度页": "官方用量事件計入圓環 · 兩檔額度另見額度頁",
            "计入圆环": "計入圓環",
            "Cursor 用量暂不可用": "Cursor 用量暫不可用",
            "会只读本机 Cursor 登录态，向 cursor.com 查询两档额度和官方用量事件。用量事件会计入圆环。登录态不落盘、不上传第三方。该接口非官方，可能随时失效。": "會只讀本機 Cursor 登入態，向 cursor.com 查詢兩檔額度和官方用量事件。用量事件會計入圓環。登入態不落盤、不上傳第三方。該介面非官方，可能隨時失效。",
            "填写 Coding Plan API Key，只进钥匙串": "填寫 Coding Plan API Key，只進鑰匙圈",
            "粘贴 ~/.kimi 的 access_token，不要用开放平台 key": "貼上 ~/.kimi 的 access_token，不要用開放平台 key",
            "终端 grok login，或粘贴 session": "終端 grok login，或貼上 session",
            "浏览器里的短码贴回终端，不要贴到这里": "瀏覽器裡的短碼貼回終端，不要貼到這裡",
            "读取 ~/.grok/auth.json，短码不要贴到 TokenStep": "讀取 ~/.grok/auth.json，短碼不要貼到 TokenStep",
            "已读取本机 grok login，不需要往这里粘贴任何代码": "已讀取本機 grok login，不需要往這裡貼任何代碼",
            "清除密钥只在你往钥匙串里存过内容时才出现。Grok 正常走 ~/.grok/auth.json，一般看不到这个按钮。": "清除密鑰只在你往鑰匙圈裡存過內容時才出現。Grok 正常走 ~/.grok/auth.json，一般看不到這個按鈕。",
            "Grok Build 弹出的短码是给终端用的。贴回正在跑 grok login 的窗口，等它显示成功，再点重新检测。": "Grok Build 彈出的短碼是給終端用的。貼回正在跑 grok login 的視窗，等它顯示成功，再點重新檢測。",
            "一般不用填，短码不要贴到这里": "一般不用填，短碼不要貼到這裡",
            "Cursor 模型": "Cursor 模型",
            "其他模型": "其他模型",
            "自有": "自有",
            "圈数进度，颜色不按来源分段": "圈數進度，顏色不按來源分段",
            "Cursor 无本地 token，额度见右栏": "Cursor 無本地 token，額度見右欄",
            "Cursor 无本地 token，不在此列": "Cursor 無本地 token，不在此列",
            "Cursor 官方用量，计入圆环": "Cursor 官方用量，計入圓環",
            "本机登录态或手动填写 · 密钥只进钥匙串": "本機登入態或手動填寫 · 密鑰只進鑰匙圈",
            "密钥只保存在钥匙串，不会写入 settings.json": "密鑰只保存在鑰匙圈，不會寫入 settings.json",
            "保存并检测": "儲存並檢測",
            "重新检测": "重新檢測",
            "清除密钥": "清除密鑰",
            "已保存在钥匙串，重新输入可覆盖": "已保存在鑰匙圈，重新輸入可覆蓋",
            "粘贴 Coding Plan API Key": "貼上 Coding Plan API Key",
            "粘贴 Kimi access_token": "貼上 Kimi access_token",
            "打开 ~/.kimi": "打開 ~/.kimi",
            "打开 ~/.grok": "打開 ~/.grok",
            "打开终端登录": "打開終端登入",
            "或粘贴 grok session": "或貼上 grok session",
            "未配置 GLM API Key": "未設定 GLM API Key",
            "Kimi 需要 OAuth，不要用开放平台 key": "Kimi 需要 OAuth，不要用開放平台 key",
            "Grok 需要 grok login，普通 xAI key 无效": "Grok 需要 grok login，普通 xAI key 無效",
            "~/.cursor/ai-tracking/ai-code-tracking.db · 只读计数与模型": "~/.cursor/ai-tracking/ai-code-tracking.db · 只讀計數與模型",
            "一圈等于多少 Token": "一圈等於多少 Token",
            "采集与图表回溯天数（7–365）": "採集與圖表回溯天數（7–365）",
            "本版新增入口": "本版新增入口",
            "调大会增加首次采集耗时。": "調大會增加首次採集耗時。",
            "外观": "外觀",
            "主题色与语言": "主題色與語言",
            "系统": "系統",
            "简体": "簡體",
            "繁体": "繁體",
            "菜单栏或灵动岛，二选一": "選單列或靈動島，二選一",
            "位置": "位置",
            "后台节奏 · 前台打开时总会即时刷": "背景節奏 · 前台打開時總會即時刷",
            "间隔": "間隔",
            "省电策略": "省電策略",
            "电池或低电量时后台最短 30 分钟": "電池或低電量時背景最短 30 分鐘",
            "更新与启动": "更新與啟動",
            "自动检查更新": "自動檢查更新",
            "榜": "榜"
        ]
    ]
}

func L(_ key: String) -> String {
    TokenStepLocalization.text(key)
}

func LFormat(_ key: String, _ arguments: CVarArg...) -> String {
    TokenStepLocalization.format(key, arguments)
}
